on:
  pull_request:
    types: [opened, synchronize]

jobs:
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set node version
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'

      - name: Install Dependencies
        uses: npm install

      - name: ESLint
        uses: npm run lint

  evaluator_job:
    runs-on: ubuntu-18.04
    name: Evaluator job
    needs: eslint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set node version
        uses: actions/setup-node@v1.4.4
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Jest evaluator step
        run: npm run test
